### ISSUE TITLE
¿Cuando es la ultima entrega?

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#10]
Aquí dice:
https://github.com/IIC2513-2018-1/syllabus/tree/master/proyecto
Que la entrega 6 es el Lunes 19 de Junio, el problema es que el tercer lunes de Junio es 18, no 19.
Por eso quiero saber, la ulitma entrega seria el Lunes 18 de Junio, el Martes 19 de Junio, u otra fecha?

**Comment by gpvidal** [comment]
Hola Pablo!

Tienes toda la razón! La E6 es el Lunes 18 de Junio. Voy a modificar los archivos.
Muchas gracias!

Saludos,
