### ISSUE TITLE
Podrian subir el ejemplo trabajado en clase

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#11]
Estoy viendo el ejemplo hecho en clase. Este:
https://github.com/IIC2513-2018-1/my-university
Pero me gustaria ver los cambios hechos el martes para poder desarmarlos, podrian subir esos cambios?

**Comment by yoavnavon** [comment]
Hola pablo, si te fijas hay una branch dev donde están todos lo cambios. Hazle pull a esa branch y podrás ver todo.

**Comment by gpvidal** [comment]
Ahora ya está en la rama `master` :wink: 

Saludos!
