### ISSUE TITLE
Problema con "id" de las migraciones

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#13]
Tengo el siguiente problema con las migraciones.
Estoy tratando de crear una entidad con 2 llaves primarias, ambas strings, por lo que en las migraciones quito el atributo de id, y sejo los 2 strings como llaves primarias.
EL problema, es, en las rutas, node me tira error porque no existe el atributo de ID, cuando la idea es que no exista atributo de ID, con la transaccion SQL pidiendo este atributo. ¿Porque pasa esto?
¿Como se evita?

**Comment by gpvidal** [comment]
Hola Pablo,

La pregunta que inmediatamente me surge es ¿Cómo estás llamando a la ruta?
Dado que tienes una llave primaria compuesta es importante que estés recibiendo bien los parámetros que estás usando para buscar (en `ctx.params`)  y posteriormente que lo estés buscando bien. Dada la llave compuesta, no puedes buscar usando `findById` sino que tienes que usar algún otro como `findOne` o `find`.

Si esto se sigue resultando complicado, puedes evaluar usar ids y hacer consultas de esta forma. De hecho te recomiendo esto, ya que con un `id` identificas inequívocamente un recurso. Tendrías que dejar el `id` (no eliminarlo en las migraciones) y usar los otros campos para las relaciones.

Saludos!

**Comment by perojas3** [comment]
OK, entonces que pasa si se tiene id, pero no llave primaria?

**Comment by gpvidal** [comment]
Deja el ID cómo llave primaria

**Comment by perojas3** [comment]
El problema de eso es que no se pueden repetir 2 instancias donde 2 de sus atributos concuerden, si tengo 3 llaves primarias, se permitiria eso. Y si tengo solo 1, como evito que se formen las intancias?

**Comment by gpvidal** [comment]
Existen las validaciones para los modelos. Puedes revisar acá:

http://docs.sequelizejs.com/manual/tutorial/models-definition.html

**Comment by perojas3** [comment]
Gracias, lo voy a revisar
