### ISSUE TITLE
Sobre crear una plantilla para las rutas

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#14]
Tengo entendido que el objetivo de un codigo es que pueda ser lo más reusable posible, por lo que en las views, cree una "plantilla" que las views de otras entidades pueden usar, y me gustaria hacer algo similar para las rutas, sin embargo como eso es directamente javascript, en vez de html.ejs, deveria hacer funciones dentro de otras funciones, y durante las clases se dijo que no estaba bien hacer esto. Mi duda entonces es ¿Es una buena idea?, si no, ¿Entonces cual seria la forma ideal de evitar repetir codigo?

**Comment by gpvidal** [comment]
Hola Pablo,

Desde mi punto de vista, el objetivo de un código debe ser resolver el problema para el cual fue hecho :wink:  

Para el caso de las rutas que tu planteas, no sé como pretendes hacer "plantillas" de rutas. Quizás, lo más conveniente es que utilices middlewares en distintas rutas, por ejemplo, lo que vimos en clases en donde creamos un middleware que cargaba el curso requerido al editarlo y otros.

Ahora, si lo que quieres es realizar un router general, del tipo que pueda copiar el comportamiento para distintas entidades, lo puedes hacer. A lo que me refiero es que hagas un router (por ej: acciones CRUD) para todos los modelos. Sin embargo, tienes que estar seguro de que tengan exactamente el mismo comportamiento, ya que los casos particulares de cada modelo pueden ser un problema para después.

Sólo como idea, y si tu evaluación es positiva, podrías definir rutas del estilo `/:model/:action` para tomar los modelos. Ojo que esto podría traerte otras complicaciones, por ejemplo el tema de formularios (dónde hago el submit,etc) y render de vistas. Por eso debe ser un idea bien estudiada.

Saludos!
