### ISSUE TITLE
Crud sin login

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#17]
Tengo el siguiente problema, en mi implementación hay usuarios, y una identidad que tiene el id del usuario que la creo, ¿Como lo referencio con usuarios entonces?

**Comment by gpvidal** [comment]
Hola Pablo,

En la documentación de `Sequelize` aparece cómo hacer asociaciones:
http://docs.sequelizejs.com/manual/tutorial/associations.html

Saludos,
