### ISSUE TITLE
Problema con yarn start

### ISSUE THREAD

**Issue by jiaranda** [IIC2513-2018-1/syllabus#18]
Hola!
Con mi grupo tenemos un problema al ejecutar yarn start (estamos desarrollando PetCare). Tenemos, en dos computadores (ambos Mac OS High Sierra), los mismos archivos y las mismas versiones de node (8.10), yarn (1.5.1), sequelize (4.0.0) y de psql (10.3). Al correr yarn start, en uno de los computadores funciona y en el otro levanta un error. ¿Pueden ayudarnos? 😢 
![whatsapp image 2018-04-10 at 19 04 38](https://user-images.githubusercontent.com/26118758/38586088-c2e3719c-3cf2-11e8-8ea2-11cc6376a290.jpeg)
![captura de pantalla 2018-04-10 a la s 19 01 50](https://user-images.githubusercontent.com/26118758/38586101-cdfec8d8-3cf2-11e8-852d-3f650e459e37.png)

**Comment by gpvidal** [comment]
Hola!

En la foto de arriba dice que ya hay algo corriendo en el puerto 3000, por lo que podrían partir revisando por ahí :wink: 

Saludos,
Gabriel

**Comment by jiaranda** [comment]
Usamos el comando `sudo lsof -i tcp:3000 ` que encontramos en [stackoverflow](https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac) para desbloquear el puerto 3000 y ahora funciona. Gracias! 😄
