### ISSUE TITLE
Preguntas para la prueba

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#19]
Como dije en clase, dejo aquí mis preguntas de materia:

1.-¿Que significa validar un modelo?
2.- No entiendo muy bien como funcionan las migraciones. Me da la imprecion de que son instrucciones que koa crea para crear la base de datos. ¿Que más hacen? ¿Que relación tienen con el modelo?

**Comment by gpvidal** [comment]
Hola Pablo!

1.- La validaciones del modelo son aquellas restricciones que debe cumplir el modelo para que sea declarado válido. En general son un conjuto de reglas, a nivel de propiedades, que hacen que el modelo en su conjunto sea válido. Por ejemplo, en el ejemplo de clases donde agregamos sesión, el modelu usuario tiene validades.

2.- Las migraciones son un conjunto de instrucciones que representan acciones que se realizarán a nivel de base de datos. En el caso de nuestro proyecto, es `sequelize` quien provee esta funcionalidad y sirve, en particular, para:

- Registro histórico de cada cambio que se realice al esquema de la base de datos
- Cada desarrollador  puede fácilmente crear su base de datos local (y en una versión diferente si se necesita), sin la necesidad de tener una base de datos remota para mantener la sincronización
- Tener la posibilidad de, en diferentes branches de nuestro código, usar bases de datos con esquemas diferentes fácilmente

entre otras ventajas.

Saludos!

**Comment by perojas3** [comment]
Sobre las migración, cada cambio que se haga sobre la base de datos, como cambiar un atributo, o agregr/quitar uno se debe hacer en las migraciones. ¿Esto no lo hace más lento que simplmente llegar al final directamente? ¿O es inteligente y sabe como sumar las acciones para evitar modificar?

**Comment by perojas3** [comment]
Sol tengo una duda, como se hace eso de tener esquemas distintos en branches distintas. ¿Esta la limitación de no ser esquemas opuestos?

**Comment by gpvidal** [comment]
La forma recomendada de trabajo en git es tener _feature branches_, lo que se traduce en que cada funcionalidad nueva de la aplicación debería ir en una de estas _branches_. Cuando tu implementas un cambio en una migración, ese cambio sólo está en tu _branch_ y, una vez terminado, se debería pasar a la rama principal. Durante ese tiempo, hay distintos esquemas en las ramas.
