### ISSUE TITLE
yarn start y psql

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2513-2018-1/syllabus#20]
Hola, al pner yarn start me tira un error y me dice:

Cannot find module 'koa-static'

Resulta que pongo npm install koa-static, hace cosas, corro de nuevo yarn start y ,e dice:

Cannot find module 'koa-ejs', y asi sucesivamente. 

Paré de instalar todo lo que me iba diciendo que faltaba porque no estoy seguro que por ahí vaya la mejor solución a esto. ¿Alguna sugerencia?

Supuestamente instalé todos los koa que están en la wiki.

**Comment by nateare** [comment]
Hola, si ya tienes yarn instalado, puedes hacer `yarn install`, para instalar todos los paquetes necesarios para correr la app.

**Comment by nateare** [comment]
Se me olvido comentar, que antes de instalar los paquetes asegúrate de estar usando la versión correcta de node.

**Comment by jorgeriesco** [comment]
Verdad que hay que poner install antes. Igual también tenia que instalar node 8.9 pq tenia el 9.8.
Sin embargo tengo otro problema. Al poner yarn start me tira un error con la base de datos:

Entre muchas cosas dice esto:
SequelizeConnectionError: password authentication failed for user "jorge"

**Comment by gpvidal** [comment]
Hola Jorge,

Revisa (este)[https://github.com/IIC2513-2018-1/syllabus/issues/16] hilo, aquí hay una forma de solucionarlo.

Saludos,
