### ISSUE TITLE
Error al crear un nuevo registro

### ISSUE THREAD

**Issue by jiaranda** [IIC2513-2018-1/syllabus#21]
Hola!
Estamos intentando crear un nuevo usuario pero al entrar al enlace para hacerlo arroja un error que no hemos logrado solucionar: ` TypeError: Expected "id" to be defined`. Esto es lo que se muestra en la terminal: 
![captura de pantalla](https://user-images.githubusercontent.com/26118758/38703719-666efa88-3e7a-11e8-8d49-86b88c6a1342.png)
Este es el código de nuestra ruta:
`router.get('users.new', '/new', async (ctx) => {`
`    const user = ctx.orm.user.build();`
`    await ctx.render('users/new', {`
`        user,`
`        submitUserPath: ctx.router.url('users.create'),` --> linea 27 de routes/users.js
`    });`
`});`
¿Alguna solución?

**Comment by nateare** [comment]
Hola, revisa tus modelos. Si te fijas estás llamando `ctx.orm.user`, y si tu modelo en realidad se llama `User`, te tirara ese error, debería ser `ctx.orm.User.` (También puede ser por otro motivo, pero es una de las razones mas comunes).

**Comment by jiaranda** [comment]
Revisamos el modelo y se llama user.js
Estos son nuestros modelos y rutas:
![captura de pantalla 2018-04-12 a la s 18 37 25](https://user-images.githubusercontent.com/26118758/38705637-996cafe2-3e80-11e8-9d40-c5b01b6ef968.png)

**Comment by nateare** [comment]
El nombre del archivo y del modelo son distintos. En mi caso, cuando tuve ese problema del id, era por el nombre. Con nombre me refiero al que sale en el código:

![screenshot from 2018-04-12 18-40-03](https://user-images.githubusercontent.com/13096343/38705765-12f95950-3e81-11e8-8dc5-8e8b616b3652.png)

**Comment by jiaranda** [comment]
Nuestro nombre del modelo es "user":
![captura de pantalla 2018-04-12 a la s 19 52 49](https://user-images.githubusercontent.com/26118758/38708127-1e32ea8e-3e8b-11e8-8180-8468188ffc2f.png)

**Comment by gpvidal** [comment]
¿Se solucionó esto al final? Si no es así por favor reabrir
