### ISSUE TITLE
Sobre sync

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#22]
Acutalmente sequelize no le hace caso a los contraints como unique o isEmail definidos en los modelos de nuestras tablas.
Segun busque en varias partes, como por ejemplo: 
https://github.com/sequelize/sequelize/issues/1163
https://github.com/sequelize/sequelize/issues/7829

Y le agrego el sync en el modelo. Lo que hace sync es crear una tabla si no existe, y si le agrego {force: true}, entonces bota la tabla y crea otra. Solo cuando hago esto ultimo respecta el unique, pero como la tabla no tiene atributo id entonces, no puedo modificarla.
Y nunca me funciona el isEmail. ¿Alguna idea de que puedo hacer?

**Comment by gpvidal** [comment]
Pablo,

Vamos a revisar esto, favor deja las restricciones expresadas en el código solamente y actualizaremos este issue con la información.

Saludos,
Gabriel
