### ISSUE TITLE
Variables de entorno con Direnv

### ISSUE THREAD

**Issue by sgvasquez** [IIC2513-2018-1/syllabus#23]
Hola! Estoy trabajando en el proyecto, y quiero utilizar variables de entorno para poner más seguro el código. 

Estoy siguiendo https://github.com/direnv/direnv, pero cuando termino la instalación (por lo visto todo ok, porque no arroja error) no pasa nada cuando entro o salgo del directorio del proyecto. Cuando intento hacer migraciones, no carga las variables definidas y tira error de autorización.

Alguna idea o guía sobre lo que podría ser?

Saludos!

**Comment by iqacevedo** [comment]
Hola,

Lo agregaste a la consola que utilizas (La parte Setup de la página que mandaste)?, Si escribes direnv en la consola que te sale? 

Para que funcione, tienes que escribir mediante consola `direnv allow` en la carpeta del proyecto.

Saludos !

**Comment by gpvidal** [comment]
Sí, es cierto lo que dice @iqacevedo , debería faltarte la parte de [setup ](https://github.com/direnv/direnv#setup)

**Comment by sgvasquez** [comment]
Hola!

Gracias por las sugerencias, pero se arregló solo ¯\_(ツ)_/ ¯

Anoche al prender el pc empezó a cargar las variables sin ningún problema. Supongo que faltaba reiniciar el pc o algo así.

Muchas gracias!
