### ISSUE TITLE
Recargar CSS en Chrome

### ISSUE THREAD

**Issue by yoavnavon** [IIC2513-2018-1/syllabus#24]
Hola! Me pasa algo muy extraño, cada vez que hago refresh, o voy a una ruta distinta de mi aplicación, todo el css desaparece por un momento, y vuelve a aparecer. Me ocurre tanto con mi aplicación como con la de my-university de ejemplo, y el error solo pasa en chrome, en safari funciona bien. Alguna idea de que puede ser?

**Comment by iqacevedo** [comment]
Hola,

Podría ser que se demore más en cargar la página. Siempre se carga primero el html y después los archivos extra que utiliza, entre ellos el css, si todo anda rápido debería ser imperceptible notar la diferencia, pero si se demora por algún motivo es normal que ocurra lo que te está sucediendo.

Cuando tienes una conexión lenta de internet es más notorio esto, se carga la página en html  primero y de a poco va poniéndose más bonita (al cargar los archivos css) .

Saludos !
