### ISSUE TITLE
Problema con las relaciones n:n

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#25]
Ya sé que tengo 2 issues activas, pero he estado estancado con este problema casi 5 horas sin avanzar. Veran tengo una relación many to many, en la cual posee un atributo. Y soy capaz de crear instancias en la tabla y luego borrarlas, pero no puedo ni acceder al atributo desde la aplicación, ni modificarlo.
Tengo la migración de esta tabla, con atributos haciendo referencia a atributos de las 2 tablas originales, tambien tengo los 3 modelos, con los 2 modelos de las instancias haciendo referencia "belongsToMany" con "through" a la tabla de la relación, y haciendo referencia a la "foreignKey" en esa tabla.
Tambien tengo el problema de que solo puedo llamar a la referencia desde una entidad. Las entidades son "user" y "work_group". Desde un "work_group" puedo hacer .getUser, pero no he encontrado como obtener los "work_group" desde "user".

**Comment by jbsaeza** [comment]
Tengo el mismo problema :(

**Comment by gpvidal** [comment]
Hola Pablo,

Tienen una referencia `belongsToMany` en ambos lados de la relación?

Saludos,

**Comment by perojas3** [comment]
Sí:
En usuario:
`    User.belongsToMany(models.work_group, {
      through: 'user_work_groups',
      foreignKey: 'user_id',
    });`
Y en work group:

`    WorkGroup.belongsToMany(models.user, {
      through: 'user_work_groups',
      foreignKey: 'work_group_id',
    });`

**Comment by gpvidal** [comment]
Estaba pensando que dado que nombraste a tu entidad cómo `work_group` el nombre de la función es distinto y probablemente tenga un `_` por ahí.

Saludos,
