### ISSUE TITLE
No puedo ver imágenes desde el navegador

### ISSUE THREAD

**Issue by jiaranda** [IIC2513-2018-1/syllabus#26]
Hola,

Al cargar la página no puedo ver las imágenes y me muestra un error 404 en las imágenes. 
- Mis compañeros si pueden verlas.
- Las imágenes no están dañadas, en el computador si puedo verlas.
- Mi navegador es Safari. Probé con Google Chrome y tampoco funciona.

Esto es lo que veo:

En la página
![captura de pantalla 2018-04-15 a la s 22 47 21](https://user-images.githubusercontent.com/26118758/38786584-519ff4a4-40ff-11e8-87c9-08ed07c4e925.png)

En la terminal (corriendo con yarn start)
![captura de pantalla 2018-04-15 a la s 22 47 54](https://user-images.githubusercontent.com/26118758/38786587-54fe41c8-40ff-11e8-8ee6-6e65dda695aa.png)

En la consola del navegador
![captura de pantalla 2018-04-15 a la s 22 49 15](https://user-images.githubusercontent.com/26118758/38786590-5700f04c-40ff-11e8-8a20-ccec6c4dfca1.png)
¿Alguna solución? 😞

**Comment by gpvidal** [comment]
Hola!

No estará dentro de `assets/images`?

Saludos

**Comment by jiaranda** [comment]
Hice el cambio y sigue sin funcionar. En los computadores de mis compañeros no se muestra cuando ponemos `src/assets/images`.

**Comment by gpvidal** [comment]
Respetaste mayúsculas y minúsculas?

**Comment by jiaranda** [comment]
Si, aun no funciona.

**Comment by jiaranda** [comment]
Aun no me funciona corriendolo en localhost en mi computador. En Heroku y en los computadores de mis compsñeros funciona perfecto el tema de las imágenes. Alguna idea de que puede ser?

**Comment by gpvidal** [comment]
Probaste corriendo con `yarn dev`?

**Comment by jiaranda** [comment]
Lo acabo de probar y no funciona. Esto me complica porque no puedo probar bien el CSS. 😞

**Comment by gpvidal** [comment]
Estás corriendo esto en Windows?

**Comment by jiaranda** [comment]
No, está corriendo en la última versión de macOS High Sierra.

**Comment by jiaranda** [comment]
Estuve investigando y creo que puede tener que ver con el manejo de archivos estáticos (koa-static) o algo similar pero no logré darle una solución a este problema.

**Comment by gpvidal** [comment]
La verdad es que no tengo la respuesta para esto, ya que no ocupo Mac. Podría ser hasta un tema de pemisos, pero no tengo la experiencia para dar una solución en ese sistema operativo.

Ojalá algún compañero pueda ayudarte :wink:

**Comment by jiaranda** [comment]
Hola!
Por otras razones volví a instalar mi sistema operativo y comencé desde un nuevo disco sin mis datos anteriores. Aún no se por qué pero ahora puedo ver las imágenes 😃
