### ISSUE TITLE
Problemas con las llaves foreneas

### ISSUE THREAD

**Issue by jbsaeza** [IIC2513-2018-1/syllabus#27]
Cuando intento definir una clave foranea en de la siguiente manera:
`email: {
        type: Sequelize.STRING,
        references: {
          model: 'students',
          key: 'email'
        }
      }`
Al aplicar esto me tira el siguiente error:
`ERROR: there is no unique constraint matching given keys for referenced table "students"
`
Es raro por q lo he usado en otras tablas y me funciona, y la clave `email` en la tabla students la tengo de la siguiente manera:
`email: {
        allowNull: false,
        primaryKey: true,
        unique: true,
        type: Sequelize.STRING,
      }`
Cual es mi error?

**Comment by jbsaeza** [comment]
Tambien tengo un problema al migrar las tablas, el error es el orden en el que migra las tablas al parecer, debido a que una de las claves foraneas se refiere a una tabla que todavia no se a creado.
Esta revisando esta [https://github.com/trailsjs/trailpack-sequelize/issues/12](url) issue y creo que esa es la solucion a mi problema, pero no logro pillar el archivo donde aplican la solucion de al final de la issue. help :(

**Comment by gpvidal** [comment]
Hola!

Las migraciones se aplican de orden secuencial, de acuerdo al timestamp que tienen los archivos en el nombre. Muy probablemente fuiste avanzando en tu programa y "se te había olvidado agregar algo", por lo que lo agregaste pero dejaste inconsistente los modelos. Lo correcto es que vayas agregando migraciones (con los datos) para evitar que te ocurra esto.

Saludos,
Gabriel

**Comment by jbsaeza** [comment]
Logre solucionar ambos problemas :D, gracias.
