### ISSUE TITLE
Posible Error en my-university

### ISSUE THREAD

**Issue by Hernan4444** [IIC2513-2018-1/syllabus#28]
Hola, estaba revisando el código de my-university, en especial el `patch` de courses.
``` javascript
router.patch('courses.update', '/:id', loadCourse, async (ctx) => {
  const { course } = ctx.state;
  try {
    const { code, name, description } = ctx.request.body;
    await course.update({ code, name, description });
    ctx.redirect(ctx.router.url('courses.list'));
  } catch (validationError) {
    await ctx.render('courses/edit', {
      course,
      errors: validationError.errors,
      submitCoursePath: ctx.router.url('courses.update'),
    });
  }
});
```
Cuando se hace catch del error, ¿`submitCoursePath `no debería recibir el id para cuando se vuelva a oprimir funcione `loadCourse` o ¿dentro del catch ya no importa ese argumento?

Saludos ✌️

**Comment by gpvidal** [comment]
:wink: Lo probaré y te cuento!
Gracias por el feedback!

Saludos,
Gabriel

**Comment by gpvidal** [comment]
Hola Hernán!

Efectivamente olvidé agregar eso, voy a reparlo en un siguiente commit :wink: 
Gracias nuevamente!

Saludos,
Gabriel

**Comment by gpvidal** [comment]
[Aquí](https://github.com/IIC2513-2018-1/my-university/pull/5) el PR que repara el error.

Saludos!
