### ISSUE TITLE
Duda organizacion de info y sistemas de grupos y proyectos

### ISSUE THREAD

**Issue by jbsaeza** [IIC2513-2018-1/syllabus#3]
Tengo 3 dudas:
1) Respecto a la organizacion de las guias, deberia ser Ramo->semestreX->guias ayudantia 1->archivos subidos por alumnos. O una forma mas desorganizada como Ramo->semestreX->archivos subidos por alumnos. O queda a criterio nuestro?
2) La idea de hacer grupos de estudio es unicamente contactar alumnos entre si?
3) El ranking que se le asigna a los compañeros del proyecto debe ser distinto al ranking de la persona respecto a las guias q sube?

**Comment by gpvidal** [comment]
Hola!

Te respondo:

1.- Queda completamente al criterio de ustedes. Los proyectos son ambiguos en ciertos sentidos para que tengan espacios para proponer cosas.

2.- Claro, es una forma de verlo

3.- Aquí también pueden proponer. Podría ser distinto y después se agrega, o sólo agregado, etc.

Saludos!
