### ISSUE TITLE
Problema con Heroku y yarn install

### ISSUE THREAD

**Issue by jiaranda** [IIC2513-2018-1/syllabus#30]
Hola!
Estamos subiendo nuestra app a Heroku y cuando corre `yarn install` nos muestra el siguiente error:
![captura de pantalla 2018-04-16 a la s 15 44 01](https://user-images.githubusercontent.com/26118758/38828663-187a06fe-418d-11e8-8571-0ffdc92347e8.png)
Hemos buscado por todos lados y no encontramos el problema.

**Comment by gpvidal** [comment]
Instalaron alguna dependencia o algo? Ya se arregló?

Saludos,
Gabriel

**Comment by jiaranda** [comment]
Logramos hacerlo sin problemas, era un conflicto entre yarn y nmp
