### ISSUE TITLE
Manejo de permisos proyecto

### ISSUE THREAD

**Issue by selira** [IIC2513-2018-1/syllabus#33]
Hola!, tengo una duda con el proyecto. Para el manejo de permisos por tipo de usuario (admin o usuario normal), deberíamos usar alguna librería (como koa-permissions) o simplemente usamos las propiedades de current.user?
Saludos

**Comment by gpvidal** [comment]
Hola!

Usen las propiedades de su usuario. Además, la librería `koa-permissions` no ha sido modificada hace 2 años! :open_mouth: 

Saludos,

**Comment by selira** [comment]
ok gracias!
