### ISSUE TITLE
Como linkear a la pagina de inicio

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#35]
Tengo la siguiente duda, entiendo que la ruta a la pagina de inicio se encuentra en index.js en routes.
Mi duda es, como se puede linkear de otras rutas a esta?
Emos estado tratando durante un buen tiempo con mis compañeros.
El problema, a diferencia de una ruta normal, es que no tiene un nombre con que llamarlo usando `ctx.router.url(<name>)`. Y si se le agrega no funciona.
¿Alguna forma?

**Comment by gpvidal** [comment]
Hola Pablo,

Intentaste con `ctx.router.url('/')`?

Saludos!

**Comment by perojas3** [comment]
Sí, tampoco sirve.

**Comment by yoavnavon** [comment]
Me paso lo mismo, finalmente lo que hice fue en vez de hacer `path: ctx.router.url(<name>)` por ejemplo si quisiera pasárselo a una vista, hice `path: '/' `, quizás no es la solución más correcta pero debiera funcionar.

**Comment by gpvidal** [comment]
Estimados,

Hice una prueba con lo siguiente:

En el archivo `src/routes/index.js` cambié esto:

```javascript
router.get('/', async (ctx) => {
  await ctx.render('index', { appVersion: pkg.version });
});
```

por:
```javascript
router.get('home', '/', async (ctx) => {
  await ctx.render('index', { appVersion: pkg.version });
});
```
posteriormente, en el archivo `src/routes/courses.js` pude obtener la ruta de esta forma:

```javascript
ctx.router.url('home');
```

Saludos!

**Comment by perojas3** [comment]
Ya intente lo que dijo profe, pero eso por si solo no era suficiente. Terminaba entregandome como direccion "//", lo cual no lleva a nada.
Lo que me acava de funcionandome (hace literalmente unos segundo) es cambiar routes.js, de:
`router.use('/', index.routes());`
a:
`router.use('', index.routes());`
Bueno, eso seria.

**Comment by gpvidal** [comment]
Pero Paaablo tu problema era la ruta que entregaba!  Me alegro de todas formas que lo hayas solucionado :smile:
