### ISSUE TITLE
Package Permitidos (CSS)

### ISSUE THREAD

**Issue by nateare** [IIC2513-2018-1/syllabus#37]
Hola, quería saber si se puede utilizar el package `styled-components`, para generar componentes. En teoría aún estaríamos escribiendo el css a mano, solo que en otro lugar (No es para usarlo en toda la app, pero si en algunas vistas). :innocent:

**Comment by gpvidal** [comment]
Lo siento, pero en esta ocasión deben utilizar el soporte de CSS incluído en el template.

Saludos!

**Comment by nateare** [comment]
Está bien, no perdía nada intentando jajaja

Gracias, saludos
