### ISSUE TITLE
Dudas para la entrega 3.

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#39]
Tengo estas dudas para la entrega 3.
1.- Queremos hacer logout, el cual utliza el metodo delete, para eso hacemos un input submit, pero este no tiene el formato requerido, nos gustaria colocar un <a> con href, pero eso solo puede ser post o get, no delete. ¿Como se hace?
2.- El lint da problema por querer hace un wait dentro de un loop, ¿Como se evita eso?
3.- El link nos tira error por hacer ++ el i de un en for, ¿Como se hace entonces?
4.- Queremos hacer una barra lateral que este precente en ciertas views, esta barra tiene links, pero no sabemos como entregarle estas rutas sin nesesidad de agregar lo mismo dentro de cada controlador, ¿Como se deberia poder hacer un controlador "General" para esta barrra lateral?

**Comment by gpvidal** [comment]
Hola Pablo,

> 1.- Queremos hacer logout, el cual utliza el metodo delete, para eso hacemos un input submit, pero este no tiene el formato requerido, nos gustaria colocar un con href, pero eso solo puede ser post o get, no delete. ¿Como se hace?

No entiendo qué significa que no tenga el formato requerido. Si vas a utilizar un link, eso sólo hará una acción de GET, por lo que si quieres hacerlo así deberías cambiar el método en el router de `delete` a `get`

> 2.- El lint da problema por querer hace un wait dentro de un loop, ¿Como se evita eso?

Sí, en general al linter no le gusta esa forma. Pero con esta no tendrías problemas:

```javascript
[...]
const promises = [];
for (let i = 0; i < <length>; i += 1) {
    promises.push(<promesa>);
}

return Promise.all(promises);
``` 
`Promise.all()` retorna una promesa cuando todas las entregadas en un array han sido resueltas.

> 3.- El link nos tira error por hacer ++ el i de un en for, ¿Como se hace entonces?

` i += 1);`

> 4.- Queremos hacer una barra lateral que este precente en ciertas views, esta barra tiene links, pero no sabemos como entregarle estas rutas sin nesesidad de agregar lo mismo dentro de cada controlador, ¿Como se deberia poder hacer un controlador "General" para esta barrra lateral?

Tal como te lo indiqué en clases puedes hacer un template que cargue las rutas que quieres (y cargarlo en otro template). Eso sí debes pasarle las cosas que necesita, por ejemplo, funciones para armar rutas dinámicas.

Saludos,
Gabriel

**Comment by perojas3** [comment]
Con la 1, es sobre html, es hacer logout, lo cual es una función `del`, pero no queremos linkearla a un:
```
                        <form action="<%= destroySessionPath %>" method="post">
                            <input type="hidden" name="_method" value="delete" />
                            <input type="submit" value="Logout" />
                        </form>
```
`En vez deseamos hacerlo con algo así: <a href="<%- destroySessionPath %>" >Log out</a>`

Con la 4, a que se refieren con un template? Es que no lo visualizo.

**Comment by gpvidal** [comment]
Hola Pablo nuevamente :)

Es imposible, usando sólo HTML, lo que quieres hacer. Los link sólo realizan acciones GET.

Con respecto a la 4, es muy similar a lo que se hace actualmente en "My University", en donde se asignan propiedades en el router "central" (en un middleware) y esas variables están disponibles en el  template (por ejemplo, cuando imprime el nombre del usuario)

Saludos,
Gabriel
