### ISSUE TITLE
Sobre el grafico ER

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#4]
Estoy usando esto: https://erdplus.com/#/ , y de default hace que las relaciones tengan nombre, con un rombo.
Tengo 2 preguntas:
-¿Es necesario esto colocar el rombo con el nombre de la relación?
-La pagina utiliza un sistema de un triangula y una linea para representar las relaciones 1:1, 1:n, y n:n ¿Esta bien así, o es mejor colocar el 1 y el n?

**Comment by gpvidal** [comment]
Hola!

- En general el rombo es una forma de representar las relaciones. Otra es que tu puedes colocar, en la línea que une ambas entidades, como se relacionan ambas. En cualquier caso, creo que el nombre de la relación (ya sea en rombo o línea) le agrega una mejor comprensión a tu diagrama por lo que está bien si lo usas. Ahora, es importante que si, la relación tiene algún atributo, ocupen el rombo para representar la relación y le agregan al rombo el atributo, ya que eso en general se mapea a una nueva tabla.

- Sí, es válido esa forma de representar la cardinalidad. Coloquialmente se le conoce como pata de gallo porque eso parece cuando se representa una relación de n entidades.

Saludos!
