### ISSUE TITLE
Problemas con las relaciones

### ISSUE THREAD

**Issue by roy350** [IIC2513-2018-1/syllabus#40]
Hola!, tengo la duda en que al crear, por ejemplo un producto que lo debo conectar con un tag(etiqueta), me genera un problema con darle el productId al tag, ya que en el momento de hacer el "post" del tag, no tengo acceso al producto que quiero, que es distinto al caso de un currentUser en que todos los parametros de este, estan en el ctx.session, y así conectarlo de manera fácil con los productos que este crea. Muchas gracias de antemano!

**Comment by gpvidal** [comment]
Hola!

Cuál es la ruta que estás utilizando para el post del tag?

Saludos,

**Comment by roy350** [comment]
Desde el form de productos, estoy utilizando un submitTagPath, para "crear" un tag si es que el producto existe, mi problema es que no entiendo porque esta realizando un post a products/:id y no a donde deberia, quizas me falta definir alguna relacion, o nose
```<div>
    <form action="<%= submitTagPath %>" method="post">
      <div class="field">
        <label for="name">Tag</label>
        <input type="text" name="name" value="<%= tag.name %>" />
      </div>
      <div class="field">
        <input type="hidden" name="productId" value="<%= product.id %>"><%= tag.productId %>
      </div>
    <button type="submit" name="create_tag" value="Create_Tag" /> Create Tag
    </form>
  </div>```
Este es el codigo al final del form de products

**Comment by gpvidal** [comment]
Creo que lo resolvimos después de clases. En caso de que sigas con la duda, puedes reabrir este issue :wink:

**Comment by roy350** [comment]
Profesor! me queda una duda con lo discutido en el codigo cuando en productos agregue la siguiente linea
```router.use('products/:id/tags',loadProduct, tagRouter.routes());```

tengo el problema de que ese id no esta definido, ya que en ningun momento se lo pase y no entiendo como hacerlo, ya que a diferencia de un patch o del que ahi con un Path le das la funcion a ejecutar, esta al ser un use no posee un "nombre" por decirlo de alguna forma, un ejemplo de lo que me refiero es esto
```editProductPath: product => ctx.router.url('products.edit', { id: product.id }),```
este Path llama a la funcion de nombre "products.edit la cual se define como
```router.get('products.edit', '/:id/edit', loadProduct, async (ctx) => {...```
aqui el primer parametro es el nombre de la funcion a llamar el cual no poseo en un use, muchas gracias de antemano! :D

**Comment by roy350** [comment]
Profesor gracias por la aclaración, pero el momento de ejecutar esta linea:
```router.use('products/:id/tags',loadProduct, tagRouter.routes());```

me dice que "id is not defined" y esto es debido a que no se lo estoy dando como en el caso de otras funciones que le describi anteriormente. Entonces de todas formas debo darle ese id al router.use

**Comment by gpvidal** [comment]
Revisa [esta] (https://github.com/IIC2513-2018-1/syllabus/issues/42) issue, ahí está exactamente el tema que planteas (creo).

Saludos,

**Comment by roy350** [comment]
Pero basicamente eso es lo mismo que tengo, en el router de product al principio tengo
```const tagRouter = require('./tags');```
y al final
```router.use('products/:id/tags',loadProduct, tagRouter.routes());```

**Comment by gpvidal** [comment]
Pero el error cuando aparece?

**Comment by roy350** [comment]
Profesor, lamento no haber comentado más, estuve un poco ocupado, ahora volviendo al proyecto, el error aparece apenas cargo la pagina, basicamente por que la ultima linea de ```router.use('products/:id/tags',loadProduct, tagRouter.routes());``` no le doy el id de ninguna forma, entonces lo que se me ocurrio fue en el metodo de create poner lo siguiente
```const product = ctx.orm.product.build(ctx.request.body);
  try {
    await product.save({ fields: ['name', 'stock', 'description', 'price', 'active', 'merchantId'] });
    ctx.state.product = product;
    console.log(ctx.state.product.id);
    router.use('products/' + ctx.state.product.id + '/tags', tagRouter.routes());
    ctx.redirect(ctx.router.url('products.list'));``` 
El problema es que no da error, pero no se crea la ruta y le hize un console.log(ctx.state.product.id), para ver si era el id correcto y si lo es, no se que podria estar fallando ahora

**Comment by roy350** [comment]
Profesor, ya arregle mi problema!
