### ISSUE TITLE
Problemas al obtener todas las instancias de una tabla

### ISSUE THREAD

**Issue by jbsaeza** [IIC2513-2018-1/syllabus#41]
Tengo un extraño problema, en routes, si intento hacer getAll() de la tabla "classes", mi tira error dado que al hacer la consulta en sql:
 `SELECT "id", "initials", "year", "semester", "createdAt", "updatedAt", "courseId" FROM "Classes" AS "Class";`
Esta falla dado que la tabla "classes" no tiene la columna "coursesId".
El problema es que en ningun momento se crea la tabla con esta columna, por lo que no se por que la consulta en sql pregunta por este header y no hace "SELECT * FROM Classes".
Una solucion alternativa a este problema es hacer las consultas SQL directamente a la db, pero he tenido problemas en encontrar como hacer esto. help :(

**Comment by BaaltRodrigo** [comment]
Hola, no tengo todas las respuestas pero si te puedo ayudar con la ultima parte :D!

Para entrar a la base de datos solo debes ingresar a postgres desde la terminal y hacer la consulta dentro de la db allí.
Por ejemplo, desde Ubuntu para entrar a la bd mediante la terminal puedes hacerlo con
`psql <db name>`
Luego dentro puedes hacer las consultas igual que en SQL

**Comment by jbsaeza** [comment]
Tenia que ver con el modelo, habíamos definido las relaciones en ambos lados y eso causaba el error.
