### ISSUE TITLE
Nested Routes - Id no está definido

### ISSUE THREAD

**Issue by sgvasquez** [IIC2513-2018-1/syllabus#42]
Hola! Como grupo queremos que para acceder a las guías de cierto curso se haga mediante la ruta /courses/:id/guides, pero al hacer eso arroja "TypeError: Expected "id" to be defined".

El ejemplo que dan en el ReadMe de Koa no define en ningún lado el id del recurso padre, por lo que no śe exactamente que estoy haciendo mal. ¿Alguna idea de qué no estoy haciendo?

Gracias!

**Comment by sgvasquez** [comment]
Por ahora solo estoy definiendo las rutas, aun no accedo al parámetro en ningun archivo.
Lo que tengo en routes.js:

`router.use('/', index.routes());`
`router.use('/courses/:id/guides', guides.routes()); /* Esta es la única referencia a id */`
`router.use('/courses', courses.routes());`
`...`

Tengo que redefinir las rutas en routes/guides.js? Ahora solo estoy buscando poder acceder a la ruta, no quiero hacer nada con el id (todavía).

**Comment by gpvidal** [comment]
Entiendo. Y qué haces en ese router (guides)? tienes algo definido para `GET '/'`?

**Comment by gpvidal** [comment]
Muy probablemente lo que esté pasando es que, dado que definiste:
```javascript
router.use('/courses/:id/guides', guides.routes()); /* Esta es la única referencia a id */
router.use('/courses', courses.routes());
```
Hay una confusión en el router. Quizás lo más recomendado sea definir la ruta `:id/guides` dentro del router de `courses`, importando el router de `guides`.

Saludos,

**Comment by sgvasquez** [comment]
Ahí si pude acceder a la ruta :)

Esto no significará un problema cuando quiera acceder a recursos más anidados todavía? Asumiendo que quiera acceder a los comentarios de una publicación de una guía de un curso, `/courses/:cId/guides/:gId/issues/:iId/comments/:comId` tendré que definir todas las rutas dentro del router de curso? No será muy engorro?

Gracias!

**Comment by gpvidal** [comment]
En teoría las issues son de la guía y, en tu `state`, deberías tener la referencia a la guía del curso en específico.

Saludos,

**Comment by sgvasquez** [comment]
Gracias!
