### ISSUE TITLE
Query en psql

### ISSUE THREAD

**Issue by tamycova** [IIC2513-2018-1/syllabus#43]
Hola!

Hay alguna forma de hacer una query directamente en la base de datos sin tener modelo?
No encontré la forma de hacerlo, es para eliminar algo de la tabla de asociaciones (que solo se usa para asociar un n:n). Por ahora tuve que hacer un modelo para la tabla y ahi hago delete con ctx.orm, pero me gustaría poder hacerlo directamente para no tener un modelo que simplemente es una asociación. 

gracias!

**Comment by gpvidal** [comment]
¿Es una tabla que se creó automáticamente? Al menos en ubuntu debes ingresar los siguientes comandos:

```bash
$ sudo -i -u postgres
$ psql
```

Y ahí ya tienes acceso a la línea de comandos del servidor de postgres.

Otra cosa que puedes hacer es borrar la base de datos (`dropdb`), crearla (`createdb`), correr las migraciones y finalmente correr las seeds.

Saludos,
Gabriel

**Comment by tamycova** [comment]
@gpvidal si! Esta es la situación:

Tengo un modelo X N:N con Y, a través de la tabla XY (esta tabla se crea al migrar, pero se usa automáticamente al agregar una asociación, no es necesario que tenga modelo, no tiene features extra solo Xid e Yid. 

El usuario puede editar cuales asociaciones tiene X con Y, y puede sacarle asociaciones. En ese caso me gustaría poder hacer directamente en psql (pero desde las rutas) : "Delete Z from XY where Z.Xid == 10", por ejemplo (que en mi mente sería lo más correcto porque es una tabla sin modelo). 

El problema es que desde routes no encuentro la forma de comunicarme directamente con mi db, solo puedo hacerlo a través de ctx.orm sin embargo ctx.orm (a mi parecer) solo me permite hacer querys sobre las tablas que tienen modelo. 

Por ahora mi solución fue simplemente hacer el modelo XY, y ahi le hago el delete con ctx.orm. No me gusta esta solución porque me hace crear un modelo que no debería estar, es solo una tabla de asociación. Además me parece contraintuitivo no poder acceder directamente a mi bases de datos si lo deseo.

Entonces mi pregunta es, si se puede, desde el código, no a través de la línea de comandos, hacer una query directamente en psql sin pasar por el orm. 

Ojalá ahi se haya entendido mejor!

Gracias!

**Comment by gpvidal** [comment]
Lo que se me ocurre es que hagas lo siguiente:

```javascript
// Desde el modelo Y
Y.removeZ()

// Desde el modelo Z
Z.removeY()
```
Podrías probar y contarnos cómo te fue :wink: 

Saludos,

**Comment by itoresano** [comment]
> Entonces mi pregunta es, si se puede, desde el código, no a través de la línea de comandos, hacer una query directamente en psql sin pasar por el orm.

http://docs.sequelizejs.com/manual/tutorial/raw-queries.html  Te sirve esto?

**Comment by gpvidal** [comment]
Voy a cerrar este issue por inactividad. Cualquier cosa pueden volver a postear.
