### ISSUE TITLE
Sobre Classes, Ids yCSS

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#44]
Tengo las siguiente dudas del tema.
1.- Entiendo que class se le puede alicar a muchos tags, mientras que id es unico. Mi duda al respecto es ¿Cuando es buena practica usar cada cual? y ¿Porque es así? Lo digo en el sentido de, si siempre uso clases distintas tendra el mismo efecto de usar ids. ¿Porque, en vez de usar id, no se usa una clase unica cada vez que se desea dar estilo unico a un elemento.?
2.- En clase vimos que nunca debiamos usar cierto elemento de CSS ¿Era class? Si no, ¿Cual era?
3.- ¿A que tags de html se le puede agregar clases e ids?
Busque aquí:
https://www.w3schools.com/tags/default.asp
Las principales serian:` <a>,<b>,<blockquote>,<body>,<h1> to <h6>,<head>`.
¿Alguna más relevante?

**Comment by gpvidal** [comment]
> Entiendo que class se le puede alicar a muchos tags, mientras que id es unico. Mi duda al respecto es ¿Cuando es buena practica usar cada cual? y ¿Porque es así? Lo digo en el sentido de, si siempre uso clases distintas tendra el mismo efecto de usar ids. ¿Porque, en vez de usar id, no se usa una clase unica cada vez que se desea dar estilo unico a un elemento.?

Claro que puedes usar siempre clases únicas para cada elemento. Sin embargo, hay casos en que sabes que el elemento será el único y quieres identificarlo de forma rápida. Para esto se utiliza el id.

> En clase vimos que nunca debiamos usar cierto elemento de CSS ¿Era class? Si no, ¿Cual era?

No es que nunca deban usarlo, pero deben evitarlo. Es la propiedad `style` de los elementos HTML, ya que los estilos generalmente deben ser agregados en un archivo aparte, para no mezclar estructura y diseño.

> ¿A que tags de html se le puede agregar clases e ids?

De los que pusiste en la lista el `<b>` JAMAS! mis ojos sangran de solo verlo. El <b> es para colocar el texto en negrita, pero yo sé que tu JAMAS de los JAMASES utilizarás ese tag porque los niños grandes usamos CSS.

De la lista de faltan varios, divs, sections, article, p, selects, ul, li, etc.

Saludos,
