### ISSUE TITLE
Dudas de la I2

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#45]
Tengo las siguientes dudas para la I2.
1.- Sobre la sesion, entiendo lo de las cookies, pero al nivel de nuestro proyecto, todo eso se encarga Koa-session, de enviar la cookie con el codigo adecuado, y pedir la cookie cuando es nesesario ¿Verdad?.
2.- Otra duda al respecto de la seccion, es: ¿Cuando se le pide la cookie al cliente? Una sola vez cada que te conectas, o multiples veces al hacer cada request?
3.- Sobre mails, entiendo que hay un protocolo global de como mandar mails. Pero sobre el proyecto, en que parte de myUniversity se esta efectivamente mandando mails, `views/email/example.html.ejs` es un template de los mails, y en `views/email/example.html.ejs` se configura, pero una vez con esto, como se manda el mail?
4.- Entiendo que cuando no se declara una variable, javascript lo interpreta como una variable global. ¿Cuando se deve hacer esto, o es siempre mala practica?
5.- Sobre el ultimo ejercicio de objetos, ¿Porque el cuak de 2 patos distintos son diferentes?
6.- Hasta que clase entra, ¿Objetos o cliente?

**Comment by gpvidal** [comment]
> 1.- Sobre la sesion, entiendo lo de las cookies, pero al nivel de nuestro proyecto, todo eso se encarga Koa-session, de enviar la cookie con el codigo adecuado, y pedir la cookie cuando es nesesario ¿Verdad?.

Exacto!

> 2.- Otra duda al respecto de la seccion, es: ¿Cuando se le pide la cookie al cliente? Una sola vez cada que te conectas, o multiples veces al hacer cada request?

En verdad tu nunca se la pides. Cuando el servidor deja una cookie en el cliente, este está obligado a enviársela en los siguientes requests.

> 3.- Sobre mails, entiendo que hay un protocolo global de como mandar mails. Pero sobre el proyecto, en que parte de myUniversity se esta efectivamente mandando mails, views/email/example.html.ejs es un template de los mails, y en views/email/example.html.ejs se configura, pero una vez con esto, como se manda el mail?

En el template del curso está implementada una función que se llama `ctx.sendMail()`, la cual se utiliza para enviar correos. En MyUniversity hicimos un ejemplo que enviaba correos cuando un usuario hacía login. Creo que si revisas ese ejemplo podría quedarte más claro :wink: 

> 4.- Entiendo que cuando no se declara una variable, javascript lo interpreta como una variable global. ¿Cuando se deve hacer esto, o es siempre mala practica?

Yo, personalmente, no lo recomendaría nunca. Principalmente porque cuando tienes un código de 5 líneas es fácil detectar, pero ya con uno de cientos (y más) es mucho más complejo detectar porqué una variable no tiene el valor que uno le había asignado varias líneas de código arriba.

> 5.- Sobre el ultimo ejercicio de objetos, ¿Porque el cuak de 2 patos distintos son diferentes?

Porque al crear un objeto `Duck`, estás creando siempre una función cuak.

> 6.- Hasta que clase entra, ¿Objetos o cliente?

Cliente JS, clase donde vimos jQuery. No entra React!

Saludos,
