### ISSUE TITLE
Clase de dudas de hoy

### ISSUE THREAD

**Issue by nacosta-cl** [IIC2513-2018-1/syllabus#46]
Hoy estuve enfermo en la mañana(Comi una fruta maligna :sweat_smile:) y no pude ir a la clase de hoy, donde se respondieron dudas de la I2.
Dijeron algo imprescindible?
Gracias!

**Comment by gpvidal** [comment]
Sí, que como siempre hagan los ejercicios de clases :wink: 

Saludos,
