### ISSUE TITLE
Duda prototypes

### ISSUE THREAD

**Issue by roy350** [IIC2513-2018-1/syllabus#47]
Hola! estudiando con un amigo nos surgio la duda, si tengo la funcion constructora Perro y creo un "objeto" perro a partir de esta funcion al hacer perro.__proto__ o perro.constructor.prototype o Object.getPrototypeOf(perro), que se supone que obtendre? Perro o el prototypo de perro es que ejecutando este codigo mi amigo obtiene un dato distinto al mio
<img width="1280" alt="captura de pantalla 2018-05-15 a la s 22 34 54" src="https://user-images.githubusercontent.com/20785160/40093760-9fef647e-5891-11e8-89ec-0e1b28093773.png">
![whatsapp image 2018-05-15 at 22 35 26](https://user-images.githubusercontent.com/20785160/40093820-de7545ba-5891-11e8-9829-01735d6733f6.jpeg)
Ahi estan las dos comparaciones, muchas gracias de antemano!

**Comment by gpvidal** [comment]
Hola @roy350 ,

El prototipo es un objeto, en ambos casos les está entregando un objeto vacío. La diferencia radica en que como están ocupando distintos programas los está imprimiendo de distinta forma.

Saludos!

**Comment by roy350** [comment]
Muchas gracias profesor y una duda mas. Prototype entra en la I2 de hoydia? Es que alguien me comento que no entraba, asi que queria saber si efectivamente es verdad o si entra en la I2. Muchas gracias!

**Comment by gpvidal** [comment]
Prototype **entra** en la prueba de hoy, entra hasta la clase (incluída) de Javascript en el lado del cliente (clase 10).
