### ISSUE TITLE
Duda middlewares

### ISSUE THREAD

**Issue by lucasmarinb** [IIC2513-2018-1/syllabus#48]
He leído en internet que los middlewares son funciones que pertenece a un stack y retornan un next para seguir con la siguiente función (middleware) del stack. ¿Es esto verdad? 
Más concretamente ¿Las funciones del router que responden a los métodos HTTP como "router.get"  son middleware? Porque no retornan un next.

**Comment by gpvidal** [comment]
Hola @lucasmarinb 

Efectivamente también son *middlewares*. En general nosotros hemos ocupado funciones que no requieren esperar el resultado de otro middleware para seguir su ejecución, y devolvemos promesas. Esto hace que cuando termine la ejecución de ella, pase al *middleware* siguiente.

Saludos,
