### ISSUE TITLE
Dudas finales de la prueba

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#49]
1.- ¿Que tenian en espcial la funciones flecha que las hacian funcionar mal en objetos?
2.- ¿En donde vimos lo del manejo de archivos, no lo encuentro?
3.- ¿En que sala es la prueba?

**Comment by gpvidal** [comment]
>  1.- ¿Que tenian en espcial la funciones flecha que las hacian funcionar mal en objetos?

Ver archivo `C10 - JavaScript - Prototype - Solucion.ipynb` de la clase 09

> 2.- ¿En donde vimos lo del manejo de archivos, no lo encuentro?

Manejo de archivos?

> 3.- ¿En que sala es la prueba?

BC24

Saludos,
