### ISSUE TITLE
Sobre Use cases

### ISSUE THREAD

**Issue by tamycova** [IIC2513-2018-1/syllabus#5]
En el enunciado piden Use cases, pero hay muchas formas de hacerlos (diferentes formatos dependiendo de a quien se pregunte, diagrama vs texto, etc). Hay un formato específico o mientras quede claro los actores y funcionalidades esenciales está correcto? No se necesitan user stories cierto?
PD: No le pude poner label a la issue creo que esta deshabilitado.

**Comment by gpvidal** [comment]
Hola Tamara,

Los casos de usuarios tiene en general un id, nombre, descripción, actores involucrados, un flujo (básico), precondiciones, postcondiciones. La idea es que puedan definir esto para su proyecto en una pequeña colección de tablas (una para caso de uso) que indiquen las cosas de arriba.

Pueden ser más detallistas e incluir más información o un diagrama, como ustedes prefieran.

Y no, no se necesitan user stories.
