### ISSUE TITLE
Sobre la entrega 4 (jquery y algo más)

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#50]
Tengo la siguiente duda con usar jquery en la aplicación web. Entiendo que hay que selecciónar en el header el archivo js. Sin embargo, en las views solo se carga el body, haciendo que solo se pueda seleccionar un archivo js con jquery por aplicación web. Mi duda es ¿Como se hace para tener archivos de jquery distintos en views diferentes?

Y, a demas de esto, entiendo que en routes.js se define un template con router.use, pero, este es el unico template que conosco que se puede usar. ¿En que otros contextos (ejemplo, rutas eespecificas) se pueden usar templates y como?

**Comment by gpvidal** [comment]
> Tengo la siguiente duda con usar jquery en la aplicación web. Entiendo que hay que selecciónar en el header el archivo js. Sin embargo, en las views solo se carga el body, haciendo que solo se pueda seleccionar un archivo js con jquery por aplicación web. Mi duda es ¿Como se hace para tener archivos de jquery distintos en views diferentes?

¿Qué estás pensando hacer?

> Y, a demas de esto, entiendo que en routes.js se define un template con router.use, pero, este es el unico template que conosco que se puede usar. ¿En que otros contextos (ejemplo, rutas eespecificas) se pueden usar templates y como?

Pablo, puedes revisar estos dos issues publicados por tus compañeros, que tienen información que podrían ser útil #40 y #42

**Comment by perojas3** [comment]
1.- Estoy pensando hacer un boton en la barra lateral que al precionarlo se muestren las suscripcione(entre otros) del usuario registrado. Para hacer eso dinamico se requiere HTML, pero si lo hago con solo 1 archivo js con jquery, entonces como podre modularizarlo en otras paginas que no lo usen?

2.- No tiene que ver con eso, tiene que ver con el src/routes.js, en este se definen cosas que van a estar presentes en todas las vistas de la aplicación, se supone que eso es un template ¿Verdad?.
Entonces, ¿Como hago otro?

**Comment by gpvidal** [comment]
> 1.-  Estoy pensando hacer un boton en la barra lateral que al precionarlo se muestren las suscripcione(entre otros) del usuario registrado. Para hacer eso dinamico se requiere HTML, pero si lo hago con solo 1 archivo js con jquery, entonces como podre modularizarlo en otras paginas que no lo usen?

Recuerda que con `jQuery` tienes que colocar un selector. Si ese selector no está, entonces no se aplica ese comportamiento.

2.- No tiene que ver con eso, tiene que ver con el src/routes.js, en este se definen cosas que van a estar presentes en todas las vistas de la aplicación, se supone que eso es un template ¿Verdad?.
Entonces, ¿Como hago otro?

Ahh ya te entendí. Lo que tu preguntas es lo que está escrito en My University en ese archivo:

```javascript
router.use(async (ctx, next) => {
  Object.assign(ctx.state, {
    currentUser: ctx.session.userId && await ctx.orm.user.findById(ctx.session.userId),
    newSessionPath: ctx.router.url('session.new'),
    destroySessionPath: ctx.router.url('session.destroy'),
    coursesPath: ctx.router.url('courses.list'),
  });
  return next();
});
```

Lo que podrías hacer es muy similar a lo que está en la vista de edit (si entiendo bien), ya que por ejemplo en `/src/routes/courses.js`, en el código del edit, yo le paso un objeto `course` con la información. En esa vista hicimos un `<%- include('_form') %>`, que carga el archivo `_form.html.ejs` y le pasa las variables.

Si requieres hacer esto para cada vista autenticada, puedes agregarlas al *middleware* que está arriba y luego el contenido de lo que deseas mostrar al archivo `layout.html.ejs`, en donde puedes revisar si hay un usuario y, si está, poder desplegar los enlaces.

Saludos,
Gabriel
