### ISSUE TITLE
Pasar variables en JS desde el server al lado del cliente

### ISSUE THREAD

**Issue by lhcubillos** [IIC2513-2018-1/syllabus#51]
Hola, cuál es la forma más correcta de pasar las variables en JS hacia el lado del cliente? Puedo usarla dentro del html con los tags <% %>, pero en un script no sé como hacerlo.

Gracias!

**Comment by gpvidal** [comment]
Hola @lhcubillos ,

¿Por qué querrías pasar una variable a JS? Supongo que puedes hacer, por ejemplo, `<%= courses.name %>` y ¿Quieres que eso esté disponible en JS? 

Podrías escribir un script en la vista, pero queda feo ¿verdad? Estarías mezclando comportamiento con estructura. Mejor no hacerlo :stuck_out_tongue: 

Saludos,
