### ISSUE TITLE
Duda Sequelize

### ISSUE THREAD

**Issue by fgvenegas** [IIC2513-2018-1/syllabus#52]
Hola!

Estaba intentando utilizar el operador 'like' de Sequelize y segun la documentación se puede utilizar asi: 

![captura de pantalla 2018-05-18 a la s 18 36 17](https://user-images.githubusercontent.com/13748708/40261039-52fd67f0-5acc-11e8-9e98-ec29877e2b9f.png)

Pero no me queda claro como llamar a Sequelize.Op desde nuestro template
De antenamo gracias

**Comment by gpvidal** [comment]
Hola @fgvenegas ,

Creo que deberías mirar acá:
http://sequelize.readthedocs.io/en/latest/docs/querying/#where

Saludos,

**Comment by fgvenegas** [comment]
Probé con 
```javascript
    products = await ctx.orm.product.findAll({ where: { name: {$like: '%' + ctx.query.Search } } });
```
y me arroja 

`
  Error: Invalid value { '$like': '%Pancito' }
`
¿Qué estoy haciendo mal?

**Comment by cggutierrez** [comment]
También tengo duda con esto, intente usar http://docs.sequelizejs.com/manual/tutorial/querying.html y tampoco me funciono, me dio errores de que Sequelize no existe.

**Comment by gpvidal** [comment]
Pero hace la consulta SQL? (mirar consola) o se cae antes?

**Comment by gpvidal** [comment]
Sí, al final estuve leyendo en [esta](http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-security) parte de la documentación y los `$Op` van a desaparecer. 

Es por esto que deberías hacer lo siguiente:

1. Importar sequelize de esta forma (donde requieras las `Op`):
```javascript
const sequelize = require('sequelize');
```

2. Después de importar, debes obtener las `Op` de esta forma:
```javascript
const { Op } = sequelize;
```

3. Finalmente puedes ocupar las `Op`:
```javascript
const coursesList = await ctx.orm.course.findAll({ where: { name: { [Op.like]: '%a%' } } });
```

Con esto debería funcionar.

Saludos,
Gabriel

**Comment by fgvenegas** [comment]
Si funciono!

Muchas gracias :D

**Comment by gpvidal** [comment]
Ok, lo cierro entonces :wink:
