### ISSUE TITLE
Error al usar .js en un form 

### ISSUE THREAD

**Issue by dfvasquez** [IIC2513-2018-1/syllabus#53]
Hola!

Quería darle "comportamiento" al form de nuestra aplicación con jQuery, pero al agregar el script, tanto en el head como en el body, me arroja el siguiente error al cargar la página:

![image](https://user-images.githubusercontent.com/20784077/40262310-635c1292-5ad4-11e8-89c0-8f04f5a47eec.png)

He buscado en internet, reviso las rutas, archivos y no entiendo qué puede estar pasando.

Agradecería mucho si alguien me pudiese ayudar, me ha tomado un buen rato tratar de arreglar esto :(

**Comment by gpvidal** [comment]
Hola @dfvasquez 

Cargaron jQuery en su sitio?

Saludos,

**Comment by dfvasquez** [comment]
Se pone una línea antes de cargar el script, cierto?

**Comment by gpvidal** [comment]
Sí, aquí explican: https://code.jquery.com/

Saludos,

**Comment by dfvasquez** [comment]
Sí lo tenemos, de hecho me guié con los ejemplos de clases 😭

**Comment by gpvidal** [comment]
Cargaste el archivo en `/src/assets/js/index.js`?

**Comment by dfvasquez** [comment]
Nop, estaba guardando el archivo en la carpeta de la vista que quería que estuviese y lo cargo en las primeras líneas del archivo del form :thinking:

**Comment by gpvidal** [comment]
Ojo con eso @dfvasquez , Mira este [comentario](https://github.com/IIC2513-2018-1/syllabus/issues/56#issuecomment-391119998)
