### ISSUE TITLE
Problema imagenes

### ISSUE THREAD

**Issue by fgvenegas** [IIC2513-2018-1/syllabus#54]
Hola
Tengo un codigo que me permite subir imagenes a mi página y las almacena en `/assets/images/`, el problema es que cuando lo pruebo en heroku no me muestra las imagenes. Podrá tener que ver con esta línea?

```javascript
    const stream = fs.createWriteStream(path.join(__dirname + '/../assets/images', data.picture));
```

Gracias

**Comment by nateare** [comment]
Hola, tengo entendido que no se pueden subir imagenes a heroku, y por lo tanto tienes que usar algún servicio externo para almacenar imagenes. (Puede que este equivocado, pero eso hice yo)

**Comment by fgvenegas** [comment]
Servicios como el de amazon del ejemplo de clases?

**Comment by nateare** [comment]
Cualquiera sirve, yo use Google Cloud Storage

**Comment by fgvenegas** [comment]
Hay alguno que no pida tarjeta de credito? xd

**Comment by nateare** [comment]
Ni idea jajaja el de Google Cloud Storage pide pero no cobra, y si se llegara a acabar el saldo desactivan la tarjeta en vez de cobrarte sin avisarte por lo menos... Yo revise varios y no encontre ninguno que no pidiera la tarjeta :(

**Comment by iqacevedo** [comment]
Hola,

Según recuerdo cloudinary no pide tarjeta de crédito. 

Saludos !

**Comment by fgvenegas** [comment]
Hola, ya logre crear el bucket en amazon y subir fotos, pero alguien sabe como hacer que siempre sean públicas? porque no puedo acceder a ellas sin ir a la pagina y hacer make public :/
