### ISSUE TITLE
Crear asociaciones en db:seed

### ISSUE THREAD

**Issue by sgvasquez** [IIC2513-2018-1/syllabus#55]
Hola! En nuestro proyecto estamos seedeando la base de datos con un bulk insert en las tablas de la misma:

Por ejemplo

```
for (i = 0; i < 10; i++) {
      guidesData.push({
        name: faker.name.findName(),
        createdAt: new Date(),
        updatedAt: new Date(),
      });
return queryInterface.bulkInsert('guides', guidesData);

```
Si nosotros tenemos en el modelo definido una relacion belongsTo(User), como podemos hacer que al seedear ya pertenezcan a un usuario? Como todavía no son un objeto del tipo Guide, no puedo hacer un User.addGuide(GuíaReciénCreada).

Muchas gracias!

**Comment by gpvidal** [comment]
Hola @sgvasquez ,

Probaste agregando un `userId` a los campos de la guía?

Saludos,
Gabriel

**Comment by sgvasquez** [comment]
Pero eso reemplaza hacer Guide.setUser? 

Si bien puedo asignar un userId en la creación, que es lo que estamos haciendo actualmente con mi grupo, no estoy seguro si eso reemplaza efectivamente hacer una asociación de forma "limpia", o si hay atributos / relaciones que no se implementen por hacerlo de esa forma.

Saludos!

**Comment by gpvidal** [comment]
Quizás [esto](https://github.com/IIC2513-2018-1/my-university/blob/dev/src/seeds/20180429144032-enroll-students-to-courses.js) te pueda servir.

Saludos,
