### ISSUE TITLE
Problema CSS en Heroku

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2513-2018-1/syllabus#58]
Hola :)

Cuando corro la aplicación de manera local se ve todo bonito, pero cuando la subo a heroku todo el css se pierde, dejando horrible la página.

¿Alguien sabe cómo repararlo?

**Comment by gpvidal** [comment]
Hola @fringlesinthestreet ,

Lo pudiste solucionar finalmente?

Saludos,

**Comment by fringlesinthestreet** [comment]
Sí :)

Al final era un error completamente nuestro xD. El template funciona perfect...
