### ISSUE TITLE
Namespaces en el proyecto

### ISSUE THREAD

**Issue by sgvasquez** [IIC2513-2018-1/syllabus#59]
Hola! En nuestro proyecto queremos hacer namespaces (en particular de admin) para trabajar las rutas, pero no tenemos muy claro como implementarlo.

Estuve buscando, y encontré un paquete que permite hacerlo de forma "bonita": https://www.npmjs.com/package/koa-namespace, podemos usarlo?

Si no se puede, alguna alternativa que no sea copiar y pegar las rutas en N archivos distintos?

**Comment by gpvidal** [comment]
Hola @sgvasquez !

Sí pueden ocuparlo, pero es responsabilidad de ustedes configurarlo correctamente y lidiar con los errores que pudiesen tener :wink: 

Saludos,
Gabriel
