### ISSUE TITLE
Transacciones a través de la página

### ISSUE THREAD

**Issue by jiaranda** [IIC2513-2018-1/syllabus#6]
Hola!
¿Como deberíamos implementar las transacciones que se hagan a través de la plataforma? 🤔

**Comment by gpvidal** [comment]
Hola!

¿Para qué proyecto en específico?¿Puedes detallar a qué te refieres con transacciones?

**Comment by jiaranda** [comment]
Con mi grupo estamos haciendo PetCare, el tema es que deberían haber transacciones entre los distintos usuarios (como en mercado libre). Mi pregunta es: ¿que se espera de nosotros en esta funcionalidad?

**Comment by gpvidal** [comment]
@iqacevedo tienes una pregunta :wink:

**Comment by iqacevedo** [comment]
Hola, 

No se espera que tengan implementado un sistema de pagos real, pero si que tengan un sistema que simule tener uno. Deberían tener alguna forma en la que un usuario pueda "pagar" a otro y que este "pago" produzca acciones (como reservar una fecha para prestar un servicio). Espero que quede claro, si no pregunta de nuevo no más.

Saludos !
