### ISSUE TITLE
Seeds App

### ISSUE THREAD

**Issue by Diiru** [IIC2513-2018-1/syllabus#60]
Hola !

Estoy teniendo problemas para generar un seed inicial grande para la app
Investigue y encontre dos formas, una creando una lista y llenandola, y otra generando una promesa con un for adentro

Forma 1

![screen shot 2018-06-02 at 22 30 19](https://user-images.githubusercontent.com/13814193/40882576-957c6aa6-66b4-11e8-8fc8-cb41e9a44533.png)

Forma 2

<img width="757" alt="screen shot 2018-06-02 at 22 29 34" src="https://user-images.githubusercontent.com/13814193/40882578-9871dd22-66b4-11e8-91c2-e5e44dac4f05.png">

Lamentablemente tuve errores en ambas, la de la lista terminaba escribiendo "address: faker.address.streetAddress()" como si fuese una frase entera, y la de la promesa lanzaba error por usar el for.

Que necesito cambiar para que me acepte el for dentro de la promesa ?

**Comment by gpvidal** [comment]
En MyUniversity hay un [ejemplo](https://github.com/IIC2513-2018-1/my-university/blob/dev/src/seeds/20180429142240-add-students.js)

Saludos,
Gabriel

**Comment by Diiru** [comment]
Buena ! Muchas gracias, había revisado MyUniversity pero no vi esas seeds, quizás se me fue cambiar a branch Dev. 
Saludos !
