### ISSUE TITLE
¿Como hacer funcionar react?

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#61]
Veran, como se hace funcionar react, ¿Como se carga en un html para que funcione? Es que no logro hacer funcionar el ejemplo en clase.

**Comment by gpvidal** [comment]
Hola @perojas3 !

Pero si estuviste en esa clase! Puedes revisar en los ejercicios de React (en este repositorio) donde hay una guía paso a paso de cómo hacer un componente. (Ejemplo que carga posts random).

Saludos,
Gabriel

**Comment by perojas3** [comment]
Esa es la parte que sí entiendo. Sé como hacer componentes y la sintexis de react. Mi problema es como ejecutarlo, como colocarlo en un html o una aplicación para que funcione.

**Comment by gpvidal** [comment]
Pablo, está en la clase y ejercicio que te mencioné:
`syllabus/clases/11 React/react/examples/components/C11 - React - Componentes.ipynb` en la parte que dice 'Probemos!'.

Saludos,
Gabriel

**Comment by perojas3** [comment]
OK, llego a la siguiente duda, una vez que lo hago, en que archivo pongo el render?
En que lugar coloco el codigo para ejecutar el react?

**Comment by gpvidal** [comment]
Pablo,

Hay varios códigos de ejemplo, pero principalmente está el de MyUniversity. La idea es que entiendas cómo se ejecutan y cómo funcionan.

Finalmente, lo anterior está siendo evaluado en la entrega de hoy. Si tienes más dudas, siempre puedes consultar la documentación de React. En la clase de este tema, última slide, hay varios recursos.

Saludos,
Gabriel

**Comment by perojas3** [comment]
Aca esta: https://github.com/IIC2513-2018-1/my-university/blob/dev/src/assets/js/components/App.jsx.
Como se llamaria desde el codigo para que haga el "Hello to React World" en un una vista.
Eso es lo que no entiendo.
