### ISSUE TITLE
Usar parámetros de la app en React

### ISSUE THREAD

**Issue by Manuel-uc** [IIC2513-2018-1/syllabus#62]
Buenas noches:
Me gustaría usar parámetros de la app (como currentUser) en los archivos de React. ¿Es posible?
Gracias!

**Comment by gpvidal** [comment]
Hola @Manuel-uc !

Para parámetros "simples" puedes usar el método que está publicado en MyUniversity, que es con  `dataset`, (vimos un ejemplo de esto en clases). En otros casos puedes hacer una ruta a aplicación que retorne un JSON con la información que solicites.

Saludos,
Gabriel

**Comment by Manuel-uc** [comment]
Muchas gracias! ¿Que entendemos por parámetro simple?

**Comment by gpvidal** [comment]
Como números, cadenas de texto, etc. Puedes intentar pasarle objetos y ver que pasa :wink: 

Saludos,
Gabriel

**Comment by perojas3** [comment]
Y que tal funciones y objetos?

**Comment by gpvidal** [comment]
Pruebe :slightly_smiling_face:

**Comment by perojas3** [comment]
¿Como se ponen funciones y objetos en json?

**Comment by gpvidal** [comment]
@perojas3 , Tal como te expliqué hoy en clases debes exponer los datos desde tu aplicación y luego hacer un request desde React.
