### ISSUE TITLE
Manejo de Archivos

### ISSUE THREAD

**Issue by yoavnavon** [IIC2513-2018-1/syllabus#63]
Hola! Tengo la siguiente duda, al poner un form para archivos de la misma forma que en ejemplo de clases, la ruta del archivo es algo como /var/folders/d0/..., mi pregunta es, que pasa con el archivo despues? Se borra o se irán acomulando los arvhicos en este lugar?

**Comment by gpvidal** [comment]
Hola @yoavnavon !

Los archivos se van eliminando.

Saludos,
