### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Diiru** [IIC2513-2018-1/syllabus#65]
Hola!

En la C11, en uno de los ejercicios de React, uso de API's vemos que la solución hace:

`async function getRandomPost() {`
`const randomPostId = Math.floor((Math.random() * 100) + 1);`
`const response = await fetch(https://jsonplaceholder.typicode.com/posts/${randomPostId});`
`return response.json();`
`}`

Luego, nos sugieren revisar la documentación, [en donde encontré](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch):

`fetch('http://example.com/movies.json')`
  `.then(function(response) {`
    `return response.json();`
 ` })`
  `.then(function(myJson) {`
    `console.log(myJson);`
 ` });`

Si bien son similares ya que ambos hacen fetch de una promesa y luego sacan lo que quieren de la respuesta, en la primera lo guardamos en una const response.

Qué se recomienda ? Da lo mismo ? Será más inseguro dejarlo en una variable que podrían modificarnos ?

Gracias de antemano !

**Comment by gpvidal** [comment]
Hola @Diiru !

En verdad depende ya que, en el primer trozo de código, estamos ocupando `async/await` y en el segundo `.then()`. Hasta el primer `then()` de la segunda parte ambos códigos están realizando la misma operación que es retornar una promesa. Luego, el segundo trozo se encarga de mostrar el json en consola.

Se entiende? En resumen, son sintaxis distintas para trabajar con promesas.

Saludos,
Gabriel

**Comment by Diiru** [comment]
Sip, entiendo ! Gracias.

Otra cosa, del mismo ejemplo o(C11) el componente ""que aparece de la nada"", componentDidMount(), qué es ?

Lo que entendí es que es como un inicializador del fetch en el estado actual, y se identifica y coloca automáticamente por React al crear los componentes, o estoy muy perdido ?

**Comment by gpvidal** [comment]
`componentDidMount()` es un método del ciclo de vida de un componente. Puedes leer más información (y ver otros métodos similares) [aquí](https://reactjs.org/docs/react-component.html#the-component-lifecycle).

Saludos,
Gabriel
