### ISSUE TITLE
Dudas I3

### ISSUE THREAD

**Issue by Manuel-uc** [IIC2513-2018-1/syllabus#66]
Buenas noches profesor:
Tengo algunas dudas con respecto a la materia de la I3. 
-No me queda muy claro que significa la frase _properties flow down, actions flow up_
-¿Una API con Code-on-demand  significa que solo entrega la información que el cliente solicita?

Si prefiere, me las puede responder en la clase de mañana

**Comment by gpvidal** [comment]
Hola @Manuel-uc !

- Con respecto a lo primero, en palabras simples quiere decir que tu vas agregando propiedades hacia abajo (en la jerarquía de los componentes vas entregando `props` a los componentes hijos) y las acciones suben (el componente avisa de un evento - apretaron mi botón! - y alguien debe ser responsable de lidiar con él)

- No recuerdo haber mencionado eso en clases, puedes darme la referencia?

Saludos,
Gabriel

**Comment by Manuel-uc** [comment]
Perdón, error de tipeo jajaja.
Quise escribir Code on demand
_-¿Una API con Code on demand significa que solo entrega la información que el cliente solicita?_

**Comment by gpvidal** [comment]
:wink: Una API con Code On Demand, puede transferir código ejecutable a los clientes pudiendo extender su funcionalidad. Un ejemplo: Yo podría enviarle a un cliente una cadena de texto encriptada y la función para desencriptarla en la respuesta del *request*.

Saludos,
Gabriel
