### ISSUE TITLE
Sobre hacer un "sub-json" en la api

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#69]
Tengo el siguiente problema, tendo 2 entidades, course y guide, con una relación 1:n. En la apí de course quiero colocar una lista de los json de sus guide. Sin embargo, no sé como colocar en el codigo de tal foma, que solo se muestren los atributos nesesarios, con link al json del respectivo guide. Por ahora hago esto:
![captura de pantalla de 2018-06-19 13-02-03 cut](https://user-images.githubusercontent.com/14139107/41612513-2a2557b2-73c1-11e8-848d-2421bbacdf37.png)
Lamentablemente este muestra todos los atributos, y no permite poner links:
![captura de pantalla de 2018-06-19 13-04-09 cut](https://user-images.githubusercontent.com/14139107/41612618-700f6722-73c1-11e8-86ba-69b2073b1f06.png)
¿Alguno sabe como hacerlo?

Otra cosa más, tengo otras dudas menores, por si alguno sabe la dejo aquí, ¿Saben como cargar los count en un include?

**Comment by gpvidal** [comment]
Hola @perojas3 ,

Te recuerdo que [jsonapi-serializer](https://github.com/SeyZ/jsonapi-serializer) formatea tu respuesta a el standard [JSONAPI](http://jsonapi.org/), en donde no veo un count.

Por otra parte, si quieres filtrar algunos campos de guide, puedes filtrarlos de tu consulta a la base de datos. Cuando tu colocas:

```javascript
include: [ctx.orm.guide]
```
Eso también puede ser un objeto de este estilo:
```javascript
include: [{
  model: ctx.orm.guide,
  fields: [... aqui los campos ...]
}]
```
Tal como aparece en la documentación de [sequelize](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll).

Saludos!

**Comment by gpvidal** [comment]
Otra cosa que olvidé mencionar, mirá como se colocan las relaciones en JSONAPI, van de una forma distinta a tu ejemplo :wink:

**Comment by perojas3** [comment]
Ok, y donde pongo los links?  Porque  Quiero saber como colocar los links a la api de cada guide.

**Comment by gpvidal** [comment]
Te toca jugar con [jsonapi-serializer](https://github.com/SeyZ/jsonapi-serializer), no tengo una respuesta ahora para ese caso.
