### ISSUE TITLE
Documentar

### ISSUE THREAD

**Issue by Hernan4444** [IIC2513-2018-1/syllabus#71]
Hola, esto puede sonar un poco tonto, pero ¿como se documenta la arquitectura?
Buscando en internet encontré:
![image](https://user-images.githubusercontent.com/15641721/41662793-de6d7322-746f-11e8-85cd-207d01801020.png)

Pero quiero saber si esto es algo esperado o de no ser así, ¿podrían recomendar alguna página que explique como documentar la arquitectura por favor?.

Gracias de antemano ✌️

**Comment by gpvidal** [comment]
Lo explicamos hoy en clases :wink: , deberíar algo simple para que el ayudante entienda cómo está armada tu aplicación.

Saludos,
