### ISSUE TITLE
Pregunta de Clase 13 API

### ISSUE THREAD

**Issue by Manuel-uc** [IIC2513-2018-1/syllabus#72]
Buenas tardes profesor:
En la clase de API, recuerdo que entro a una aplicación del browser (o una página, no recuerdo muy bien) donde introdujo su token para así poder hacer post.
Agradecería mucho si pudiera decirme que aplicación uso.
Muchas gracias
Saludos

**Comment by gpvidal** [comment]
Hola @Manuel-uc !

El que yo ocupé es un plugin para Chrome, desconozco si existe para otro navegador. Se llama `Restlet` client.

Saludos,

**Comment by nacosta-cl** [comment]
Postman es una muy buena alternativa para probar apis, y tiene para todo

**Comment by Manuel-uc** [comment]
Muchas gracias!
