### ISSUE TITLE
Duda con autentificacion

### ISSUE THREAD

**Issue by roy350** [IIC2513-2018-1/syllabus#74]
Hola! me surgio una duda, en cuanto a la autentificacion de la api, mi tema es que yo tengo 2 tipos de session, user y merchants, ambos tipos de usuarios con distitnas funcionaldades, entonces como se puede hacer la autentificacion para 2 tipos de cuenta? intente con esto pero no funciono.
```
router.use(jwt({ secret: process.env.JWT_SECRET, key: 'authData' }));
router.use(async (ctx, next) => {
  if (ctx.state.authData.userId) {
    ctx.state.currentUser = await ctx.orm.user.findById(ctx.state.authData.userId);
  }
  return next();
});

router.use('/users', usersApi.routes());

router.use(async (ctx, next) => {
  if(ctx.state.authData.merchantId) {
    ctx.state.currentmerchant = await ctx.orm.merchant.findById(ctx.state.authData.merchantId);
  }
  return next();
});

router.use('/merchants', merchantsApi.routes());
```
Lo anterior esta en el index y dentro del archivo auth.js tengo esto
```
const KoaRouter = require('koa-router');
const jwtgenerator = require('jsonwebtoken');

const router = new KoaRouter();

router.post('auth', '/user', async (ctx) => {
  const { username, password } = ctx.request.body;
  const user = await ctx.orm.user.find({ where: { username } });
  if (user && await user.checkPassword(password)) {
    const token = await new Promise((resolve, reject) => {
      jwtgenerator.sign(
        { userId: user.id },
        process.env.JWT_SECRET,
        (err, tokenResult) => (err ? reject(err) : resolve(tokenResult)),
      );
    });
    ctx.body = { token };
  } else {
    ctx.throw(401, 'Wrong e-mail or password');
  }
});

router.post('auth', '/merchant', async (ctx) => {
  const { username, password } = ctx.request.body;
  const merchant = await ctx.orm.merchant.find({ where: { username } });
  if (merchant && await merchant.checkPassword(password)) {
    const token = await new Promise((resolve, reject) => {
      jwtgenerator.sign(
        { merchantId: merchant.id },
        process.env.JWT_SECRET,
        (err, tokenResult) => (err ? reject(err) : resolve(tokenResult)),
      );
    });
    ctx.body = { token };
  } else {
    ctx.throw(401, 'Wrong e-mail or password');
  }
});

module.exports = router;
```
El tema es que puedo acceder a un funciones de merchant siendo user, entonces si supiera como solucionar este error se lo agradeceria mucho! Saludos

**Comment by roy350** [comment]
Lo que si el archivo de auth al parecerer estaria funcionando, ya que solo te entregara el token de user si eres user y el token de merchant si eres merchant, pero para las demas, no se muy bien como filtrarlas

**Comment by roy350** [comment]
Alguno sabe?

**Comment by gpvidal** [comment]
Hola @roy350 !

Creo que (viendo este trozo de código) aquí podría haber un error de modelación, ya que podría haber un parámetro como "tipo de usuario" para este caso.

Puedes agregar el parámetro `passthrough: true`, tal como lo indica la [documentación](https://github.com/koajs/jwt), para que puedas pasar el primer chequeo de seguridad. Posterior a esto deberías efectivamente chequear (antes de las rutas) si está autorizado, si existe el usuario o lanzar un error.

Esta es una solución bastante "poco elegante", pero debería funcionar.

Saludos,

**Comment by roy350** [comment]
Profesor viendo la documentacion, el tema con ```passthrough: true``` no entendi muy bien como quedaria la estructura del index.js me imagino que seria algo de este estilo
```
router.use(jwt({ secret: process.env.JWT_SECRET, key: 'authData', passthrough: true }));
router.use(async (ctx, next) => {
  if (ctx.state.authData.userId) {
    ctx.state.currentUser = await ctx.orm.user.findById(ctx.state.authData.userId);
  }
  return next();
});

router.use('/users', usersApi.routes());

router.use(jwt({ secret: process.env.JWT_SECRET, key: 'authData', passthrough: true }));
router.use(async (ctx, next) => {
  if(ctx.state.authData.merchantId) {
    ctx.state.currentmerchant = await ctx.orm.merchant.findById(ctx.state.authData.merchantId);
  }
  return next();
});

router.use('/merchants', merchantsApi.routes());
```
Pero no entiendo como seria la autorización que se deberia realizar para identificar efectivamente que el id proveniente es de un objeto ```user``` o un objeto ```merchant```

**Comment by roy350** [comment]
Profesor no se proecupe logre solucionarlo de otra manera, muchas gracias de todas formas!
