### ISSUE TITLE
Preguntas para el examen

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#76]
Ok, tengo estas dudas del examen:
1.- Bueno... ¿A que hora y en qué sala es el examen?
2.- Sobre apis, en la pauta de la I3 se usa simplemente ctx.body= objeto. ¿Esto se puede hacer directamente? ¿Que limitación tiene? ¿Se puede hacer RESTful así? 
3.- En apis, es nesesario retornar el codigo 200 de exito?
4.- Sobre apis de nuevo, a veces durante el curso escuche sobre consumir una api REST. ¿Como se hace eso? Entiendo como hacerlo con react, pero no con node.
5.- Sobre testing, ¿Es importante la sintaxis del codigo para el examen?, es que nunca lo usamos en el proyecto.
Y una coas más ¿Cuando estara la nota de la i3?

**Comment by perojas3** [comment]
Y se me olvido esta:
6.- En react, como se obtiene el curren user?

**Comment by gpvidal** [comment]
Hola @perojas3 !

Aquí las respuestas:

> 1.- Bueno... ¿A que hora y en qué sala es el examen?

Lo publicaré mañana

> 2.- Sobre apis, en la pauta de la I3 se usa simplemente ctx.body= objeto. ¿Esto se puede hacer directamente? ¿Que limitación tiene? ¿Se puede hacer RESTful así?

Sí, puede ser utilizado de esta forma. De hecho, si recuerdas la clase de API partimos haciendo esto, luego introdujimos json serializer y JSONAPI.

Se puede hacer RESTful de esta forma, pero es más trabajoso. Json Serializer hace las cosas bastante automáticas.

> 3.- En apis, es nesesario retornar el codigo 200 de exito?

En general, cuando todo sale bien (no hay excepción), Koa retorna 200 de forma automática.

> 4.- Sobre apis de nuevo, a veces durante el curso escuche sobre consumir una api REST. ¿Como se hace eso? Entiendo como hacerlo con react, pero no con node.

En ambos casos, dado que tenemos Javascript en el cliente y servidor, lo puedes hacer mediante la función `fetch` (más información [aquí](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch))

> 5.- Sobre testing, ¿Es importante la sintaxis del codigo para el examen?, es que nunca lo usamos en el proyecto.

No les voy a pedir programar tests, pero podría hacer que escriban un código que haga que ciertos tests se ejecuten con éxito o preguntarles algo más conceptual (como en la I pasada).

> 6.- En react, como se obtiene el curren user?

No puedes obtener el current user que tiene Koa directamente. Tienes dos opciones:
* Le entregas los datos del current user mediante los `datasets`
* En tu componente React incluyes una llamada a un ruta de tu aplicación en Koa que le entrega esos datos.

> Y una coas más ¿Cuando estara la nota de la i3?

Sus ayudantes, en un esfuerzo sobre-humano, esperan tener las notas de la I3 mañana en la noche. La prioridad ahora es poder entregarles las notas lo antes posible.

Saludos,
Gabriel

**Comment by perojas3** [comment]
Sobre la pregunta 6. ¿Como se hace eso de dataset a nivel de sintaxis. En que parte del codigo de node le entrego algo de tal forma que react pueda recivirlo?

**Comment by gpvidal** [comment]
@perojas3 te lo expliqué en la sesión de preguntas de la I3! Además hay un ejemplo publicado en MyUniversity :wink: 

Saludos,

**Comment by perojas3** [comment]
Ok, es que estoy viendo my university, y el ejemplo es el de hace fectch desde https://jsonplaceholder.typicode.com/posts. No encuentro en que momento es recibiendo parametros desde node.
Y segundo. ¿Qué hora termina el examen?

**Comment by gpvidal** [comment]
No entendí tu primera pregunta.
Sobre la segunda, serán dos horas de examen.

Saludos,

**Comment by perojas3** [comment]
Sobre lo primero. Estoy practicando con node. Y logro hacer todo desde la api, pero no puedo pasarle el current user ni direcciones a react. Viendo my university, no encuentro donde se le esta pasando información a react desde node, solo veo que se carga la información por medio de jsonapi y luego se coloca en el html por medio de un id. No encuentro la parte del codigo del dataset.

**Comment by gpvidal** [comment]
Pablo, creo que tienes una confusión: node funciona desde el lado del servidor y React en el lado del cliente, por lo que no puedes pasarles variables de un lado para otro directamente a menos que sea a través de los dataset, tal como lo muestran los archivos [index.html.ejs](https://github.com/IIC2513-2018-1/my-university/blob/master/src/views/index.html.ejs) y [app.jsx](https://github.com/IIC2513-2018-1/my-university/blob/master/src/assets/js/app.jsx).

Lo otro es que, tal como en ese ejercicio que esta publicado en la clase de React, en vez de ir a buscar datos a `jsonplaceholder.typicode.com` puedes ir a buscar datos desde un componente React cualquiera a tu API, y así obtener los datos necesarios.

Saludos,
