### ISSUE TITLE
Recibir objeto con react

### ISSUE THREAD

**Issue by vaguila95** [IIC2513-2018-1/syllabus#78]
Hola profe!

Estudiando para la prueba me surgió la duda sobre cómo hacer para recibir un objeto en las props. Algo de este estilo 
```javascript
<div id="react-main" info=<script>{ info1: 'esto es info importante'  }</script> ></div>
```

**Comment by gpvidal** [comment]
Solo puedes pasar strings. Aquí mayor explicación:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

Saludos,

**Comment by vaguila95** [comment]
Estaba usando JSON.stringify, pero por alguna razón me arroja error cuando hay algún espacio dentro de un string.

```javascript
<script type="text/javascript">
  document.write(`<div id="ejercicio-react-2017-2" info=${JSON.stringify([{name:'manzana',description:'Esto es una manzana'},{x:2}])}></div>`)
</script>
```

Alguna idea de por qué sucede esto?

Saludos!

**Comment by gpvidal** [comment]
Me imagino que es porque te faltan comillas dobles en lo que va dentro de info:

```
info="${JSON.stringify([{name:'manzana',description:'Esto es una manzana'},{x:2}])}"
```
