### ISSUE TITLE
Otros detalles de los diagramas ER

### ISSUE THREAD

**Issue by perojas3** [IIC2513-2018-1/syllabus#8]
Tengo otras dudas acerca de estos diagramas, relacionado con los atributos.

En un diagrama ER, permite colocar los atributos unicos subrallados. Intuyo que estos atributos serian las llaves, sin embargo, ¿Que se hace cuando se tiene más de una llave?. He pensado colocarlos dentro de solo una burbuja, pero puede con caber. Otra opción es colocarlos en distintas, pero ¿Seguira siendo "unico" cuando solo todo el conjunto es unico?

Y segundo son los atributos derivados, aquellos que provienen de otros atributos, y cullo globo es punteado. ¿Es así de simple, si un atributo es referencia a otro de otra entidad, entonces simplemente hay que tenerlo punteado?. A demas de esto me confunde que hay que hacer cuando uno de estos es parte de la llave, especialmente si la respuesta es compartir el globo.

**Comment by gpvidal** [comment]
Hola Pablo,

Puedes colocarlos en distintas burbujas (ambos subrayados) para el primer caso.

Para lo segundo, no entiendo a lo que te refieres con compartir atributos. Los atributos son propios de cada entidad o relación. Si hay un atributo, que referencia a otra entidad, debería quedar reflejada con una relación.

Saludos,
Gabriel

**Comment by perojas3** [comment]
Me refiero a esto:
![captura de pantalla de 2018-03-27 15-22-46](https://user-images.githubusercontent.com/14139107/37987054-8e4a7b4e-31d3-11e8-8f93-d063d4c09d56.png)
Como funciona esto de los atributos derivados, busque y me die que son atributos de otras entidades, por eso pregunto como funcionan?

**Comment by gpvidal** [comment]
Los atributos derivados son aquellos que se pueden calcular en base a otros atributos. Por ejemplo, si tienes una entidad Persona que tiene el atributo fecha de nacimiento, un atributo derivado sería la edad; ya que la puedes calcular en base a la fecha de nacimiento. En todo caso estos casos son bien raros.

Aquí hay una buena explicación de diagramas ER (en inglés):
https://creately.com/blog/diagrams/er-diagrams-tutorial/

Saludos!

**Comment by perojas3** [comment]
Otra pregunta más, si un atributo tiene un atributo que hace referencia a otra entidad, solo hace falta referenciarlo con una relación?
