### ISSUE TITLE
Subir Archivos Entrega a Github

### ISSUE THREAD

**Issue by Manuel-uc** [IIC2513-2018-1/syllabus#9]
Perdón si mi duda es muy trivial, pero, ¿donde subimos los archivos a nuestro repositorio de grupo? ¿Creamos una carpeta Entregas y adentro creamos una carpeta entrga1?

**Comment by gpvidal** [comment]
Del enunciado de entrega: 

> Esta es la única entrega en que en lugar de código entregarán documentos – por supuesto, en PDF. La entrega se realizará en un cuestionario en el SIDING, donde tendrán que subir un archivo zip (nombredegrupo.zip) y los tres documentos (en PDF) en su interior.

Adicionalmente pueden crear una carpeta `docs/entrega1` y los documentos en el interior. Pero **la entrega es oficialmente en SIDING**.

Saludos,

**Comment by Manuel-uc** [comment]
Lo decía por esto:
"Adicionalmente, todo tiene que ser subido igualmente a su repositorio Github que les crearemos y les enviaremos prontamente."
Muchas gracias.

**Comment by gpvidal** [comment]
Perfecto! Pensé que era una pregunta con respecto a la entrega :wink:
